In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0, 100, (10,2))

In [4]:
data

array([[19,  4],
       [ 1, 92],
       [ 4,  6],
       [52, 44],
       [30, 92],
       [41, 67],
       [71, 73],
       [66, 23],
       [51,  5],
       [ 8, 66]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing._data.MinMaxScaler

In [7]:
scaler_model.fit(data)

MinMaxScaler()

In [8]:
scaler_model.transform(data)

array([[0.25714286, 0.        ],
       [0.        , 1.        ],
       [0.04285714, 0.02272727],
       [0.72857143, 0.45454545],
       [0.41428571, 1.        ],
       [0.57142857, 0.71590909],
       [1.        , 0.78409091],
       [0.92857143, 0.21590909],
       [0.71428571, 0.01136364],
       [0.1       , 0.70454545]])

In [9]:
scaler_model.fit_transform(data)

array([[0.25714286, 0.        ],
       [0.        , 1.        ],
       [0.04285714, 0.02272727],
       [0.72857143, 0.45454545],
       [0.41428571, 1.        ],
       [0.57142857, 0.71590909],
       [1.        , 0.78409091],
       [0.92857143, 0.21590909],
       [0.71428571, 0.01136364],
       [0.1       , 0.70454545]])

In [10]:
import pandas as pd

In [13]:
mydata = np.random.randint(1, 101, (50,4))

In [14]:
mydata

array([[ 49,  59,  29,  18],
       [ 72,  94,  38,   7],
       [ 82,  59,  12,  52],
       [ 95,  48,   1,  25],
       [ 86,  25,   1,  35],
       [ 81,  99,  66,  25],
       [100,  51,  73,  19],
       [ 93,  94,  75,  63],
       [ 62,  37,  79,  13],
       [ 55,  90,  65,  62],
       [  9,  55,  78,  86],
       [  1,  25,  57,  63],
       [ 52,  41,  76,  76],
       [  2,  63,  34,  50],
       [ 92,  60,  19,   7],
       [ 23,  84,  91,  16],
       [ 16,  30,  61,  88],
       [ 82,  97,  78,  89],
       [ 32,  96,  44,  12],
       [ 86,  39,  25,  95],
       [ 79,   2,  10,  48],
       [ 91,  35,  54,  90],
       [ 75,  74,  39,  84],
       [ 30,  48,  81,  72],
       [ 73,   1,  48,  56],
       [ 34,  15,  93,  12],
       [  7,  67,  37,  76],
       [ 20,  39,  38,  35],
       [ 98,  62,   4,  35],
       [ 20,  42,  56,  95],
       [ 27,  61,  77,  84],
       [ 52,  54,  86,  77],
       [ 45,  65,  86,  78],
       [  2,  38,  91,  27],
       [ 29,  44,  76,  84],
       [ 98,  20,  23,  86],
       [ 69,  77,  64,  49],
       [ 82,  28,  81,  78],
       [ 92,  55,  11,  71],
       [ 43,  43,  41,  12],
       [ 82,   5,  90,  46],
       [ 94,   8,  96,   7],
       [  7,  39,  49,  87],
       [ 49,  44,  77,  88],
       [ 22,  62,  91,  66],
       [  7,  30,  55,  39],
       [  9,  39,  19,  28],
       [ 37,  22,  57,  28],
       [ 36,  85,  79,   8],
       [ 79,  62,   4,  97]])

In [18]:
data= pd.DataFrame(data=mydata, columns=['f1','f2','f3','label'])

In [19]:
data

     f1  f2  f3  label
0    49  59  29     18
1    72  94  38      7
2    82  59  12     52
3    95  48   1     25
4    86  25   1     35
5    81  99  66     25
6   100  51  73     19
7    93  94  75     63
8    62  37  79     13
9    55  90  65     62
10    9  55  78     86
11    1  25  57     63
12   52  41  76     76
13    2  63  34     50
14   92  60  19      7
15   23  84  91     16
16   16  30  61     88
17   82  97  78     89
18   32  96  44     12
19   86  39  25     95
20   79   2  10     48
21   91  35  54     90
22   75  74  39     84
23   30  48  81     72
24   73   1  48     56
25   34  15  93     12
26    7  67  37     76
27   20  39  38     35
28   98  62   4     35
29   20  42  56     95
30   27  61  77     84
31   52  54  86     77
32   45  65  86     78
33    2  38  91     27
34   29  44  76     84
35   98  20  23     86
36   69  77  64     49
37   82  28  81     78
38   92  55  11     71
39   43  43  41     12
40   82   5  90     46
41   94   8  96      7
42    7  39  49     87
43   49  44  77     88
44   22  62  91     66
45    7  30  55     39
46    9  39  19     28
47   37  22  57     28
48   36  85  79      8
49   79  62   4     97

In [21]:
X= data[['f1','f2','f3']]

In [22]:
X

     f1  f2  f3
0    49  59  29
1    72  94  38
2    82  59  12
3    95  48   1
4    86  25   1
5    81  99  66
6   100  51  73
7    93  94  75
8    62  37  79
9    55  90  65
10    9  55  78
11    1  25  57
12   52  41  76
13    2  63  34
14   92  60  19
15   23  84  91
16   16  30  61
17   82  97  78
18   32  96  44
19   86  39  25
20   79   2  10
21   91  35  54
22   75  74  39
23   30  48  81
24   73   1  48
25   34  15  93
26    7  67  37
27   20  39  38
28   98  62   4
29   20  42  56
30   27  61  77
31   52  54  86
32   45  65  86
33    2  38  91
34   29  44  76
35   98  20  23
36   69  77  64
37   82  28  81
38   92  55  11
39   43  43  41
40   82   5  90
41   94   8  96
42    7  39  49
43   49  44  77
44   22  62  91
45    7  30  55
46    9  39  19
47   37  22  57
48   36  85  79
49   79  62   4

In [23]:
y= data['label']

In [24]:
y

0     18
1      7
2     52
3     25
4     35
5     25
6     19
7     63
8     13
9     62
10    86
11    63
12    76
13    50
14     7
15    16
16    88
17    89
18    12
19    95
20    48
21    90
22    84
23    72
24    56
25    12
26    76
27    35
28    35
29    95
30    84
31    77
32    78
33    27
34    84
35    86
36    49
37    78
38    71
39    12
40    46
41     7
42    87
43    88
44    66
45    39
46    28
47    28
48     8
49    97
Name: label, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=101)

In [30]:
X_train.shape

(35, 3)

In [31]:
X_test.shape

(15, 3)