In [1]:
import QuantLib as ql
import pandas as pd

<h2>Date Class</h2>

In [2]:
date = ql.Date(31, 3, 2015)
print(date)

March 31st, 2015

In [3]:
print("%d-%d-%d" %(date.month(),
                  date.dayOfMonth(),
                  date.year()))

3-31-2015

In [4]:
date.weekday() == ql.Tuesday

True

In [5]:
type(date+1)

QuantLib.QuantLib.Date

In [6]:
print("Add a day       :{0}".format(date+1))
print("Subtract a day  :{0}".format(date-1))
print("Add a week      :{0}".format(date+ql.Period(1, ql.Weeks)))
print("Add a Month     :{0}".format(date+ql.Period(1, ql.Months)))
print("Add a Year      :{0}".format(date+ql.Period(1, ql.Years)))

Add a day       :April 1st, 2015
Subtract a day  :March 30th, 2015
Add a week      :April 7th, 2015
Add a Month     :April 30th, 2015
Add a Year      :March 31st, 2016

One can also do logical operations using the Date object.

In [7]:
print(date == ql.Date(31, 3, 2015))
print(date > ql.Date(30, 3, 2015))
print(date < ql.Date(1, 4, 2015))
print(date != ql.Date(1, 4, 2015))

True
True
True
True

<h2>Calendar Class</h2>

Calendar class implements the functionality of holidays for all the major exchanges.

In [8]:
date = ql.Date(31,3,2015)
us_calendar = ql.UnitedStates(ql.UnitedStates.GovernmentBond)
italy_calendar = ql.Italy()

period = ql.Period(60, ql.Days)
raw_date = date + period
us_date = us_calendar.advance(date, period)
italy_date = italy_calendar.advance(date, period)

print("Add 60 days: {0}".format(raw_date))
print("Add 60 business days in US: {0}".format(us_date))
print("Add 60 business days in Italy: {0}".format(italy_date))

Add 60 days: May 30th, 2015
Add 60 business days in US: June 24th, 2015
Add 60 business days in Italy: June 26th, 2015

The addHoliday and removeHoliday methods in the calendar

In [9]:
us_busdays = us_calendar.businessDaysBetween(date, us_date)
italy_busdays = italy_calendar.businessDaysBetween(date, italy_date)

print("Business days US: {0}".format(us_busdays))
print("Business days Italy: {0}".format(italy_busdays))

Business days US: 60
Business days Italy: 60

JointCalendar class that allows you to combine the holidays of two or more calendars.

In [10]:
joint_calendar = ql.JointCalendar(us_calendar, italy_calendar)

joint_date = joint_calendar.advance(date, period)
joint_busdays = joint_calendar.businessDaysBetween(date, joint_date)

print("Add 60 business days in US-Italy: {0}".format(joint_date))
print("Business days US-Italy: {0}".format(joint_busdays))

Add 60 business days in US-Italy: June 29th, 2015
Business days US-Italy: 60

<h2>Schedule Class</h2>

The Schedule object is necessary in creating coupon schedules or call schedules.

In [11]:
effective_date = ql.Date(1, 1, 2015)
termination_date = ql.Date(1, 1, 2016)
tenor = ql.Period(ql.Monthly)
calendar = ql.UnitedStates(ql.UnitedStates.GovernmentBond)
business_convention = ql.Following
termination_business_convention = ql.Following
date_generation = ql.DateGeneration.Forward
end_of_month = False
schedule = ql.Schedule(effective_date,
                       termination_date,
                       tenor,
                       calendar,
                       business_convention,
                       termination_business_convention,
                       date_generation,
                       end_of_month)

pd.DataFrame({'date': list(schedule)})

                   date
0     January 2nd, 2015
1    February 2nd, 2015
2       March 2nd, 2015
3       April 1st, 2015
4         May 1st, 2015
5        June 1st, 2015
6        July 1st, 2015
7      August 3rd, 2015
8   September 1st, 2015
9     October 1st, 2015
10   November 2nd, 2015
11   December 1st, 2015
12    January 4th, 2016

Demo firstDate and nextToLastDate parameters along with a combination of forward or
backward date generation rule

In [12]:
# short stub in the front
effective_date = ql.Date(1,1, 2015)
termination_date = ql.Date(1, 1, 2016)
first_date = ql.Date(15, 1, 2015)
schedule = ql.Schedule(effective_date,
                       termination_date,
                       tenor,
                       calendar,
                       business_convention,
                       termination_business_convention,
                       ql.DateGeneration.Backward,
                       end_of_month,
                       first_date)

pd.DataFrame({'date':list(schedule)})

                   date
0     January 2nd, 2015
1    January 15th, 2015
2    February 2nd, 2015
3       March 2nd, 2015
4       April 1st, 2015
5         May 1st, 2015
6        June 1st, 2015
7        July 1st, 2015
8      August 3rd, 2015
9   September 1st, 2015
10    October 1st, 2015
11   November 2nd, 2015
12   December 1st, 2015
13    January 4th, 2016

Using the nextToLastDate parameter along with the forward date generation rule creates a short
stub at the back end of the schedule.

In [13]:
# short stub at the back
effective_date= ql.Date(1,1,2015)
termination_date = ql.Date(1,1, 2016)
penultimate_date = ql.Date(15, 12, 2015)
schedule = ql.Schedule(effective_date,
                       termination_date,
                       tenor,
                       calendar,
                       business_convention,
                       termination_business_convention,
                       ql.DateGeneration.Forward,
                       end_of_month,
                       ql.Date(),
                       penultimate_date)

pd.DataFrame({'date':list(schedule)})

                   date
0     January 2nd, 2015
1    February 2nd, 2015
2       March 2nd, 2015
3       April 1st, 2015
4         May 1st, 2015
5        June 1st, 2015
6        July 1st, 2015
7      August 3rd, 2015
8   September 1st, 2015
9     October 1st, 2015
10   November 2nd, 2015
11   December 1st, 2015
12  December 15th, 2015
13    January 4th, 2016

Using the backward generation rule along with the firstDate allows us to create a long stub in the
front.

In [14]:
# long stub in the front
first_date = ql.Date(1,2, 2015)
effective_date = ql.Date(15, 12, 2014)
termination_date = ql.Date(1, 1, 2016)
schedule =ql.Schedule(effective_date,
                      termination_date,
                      tenor,
                      calendar,
                      business_convention,
                      termination_business_convention,
                      ql.DateGeneration.Backward,
                      end_of_month,
                      first_date)

pd.DataFrame({'data':list(schedule)})

                   data
0   December 15th, 2014
1    February 2nd, 2015
2       March 2nd, 2015
3       April 1st, 2015
4         May 1st, 2015
5        June 1st, 2015
6        July 1st, 2015
7      August 3rd, 2015
8   September 1st, 2015
9     October 1st, 2015
10   November 2nd, 2015
11   December 1st, 2015
12    January 4th, 2016

usage of nextToLastDate parameter along with forward date generation rule can be
used to generate long stub at the back of the schedule.

In [15]:
# long stub at the back
effective_date = ql.Date(1,1,2015)
penultimate_date = ql.Date(1, 12, 2015)
termination_date = ql.Date(15, 1, 2016)
schedule = ql.Schedule(effective_date,
                       termination_date,
                       tenor,
                       calendar,
                       business_convention,
                       termination_business_convention,
                       ql.DateGeneration.Forward,
                       end_of_month,
                       ql.Date(),
                       penultimate_date)

pd.DataFrame({'date':list(schedule)})

                   date
0     January 2nd, 2015
1    February 2nd, 2015
2       March 2nd, 2015
3       April 1st, 2015
4         May 1st, 2015
5        June 1st, 2015
6        July 1st, 2015
7      August 3rd, 2015
8   September 1st, 2015
9     October 1st, 2015
10   November 2nd, 2015
11   December 1st, 2015
12   January 15th, 2016

Below the Schedule is generated from a list of dates.

In [16]:
dates = [ql.Date(2,1,2015), ql.Date(2, 2,2015),
ql.Date(2,3,2015), ql.Date(1,4,2015),
ql.Date(1,5,2015), ql.Date(1,6,2015),
ql.Date(1,7,2015), ql.Date(3,8,2015),
ql.Date(1,9,2015), ql.Date(1,10,2015),
ql.Date(2,11,2015), ql.Date(1,12,2015),
ql.Date(4,1,2016)]

rolling_convention = ql.Following

schedule= ql.Schedule(dates, calendar,
                      rolling_convention)

pd.DataFrame({'date':list(schedule)})

                   date
0     January 2nd, 2015
1    February 2nd, 2015
2       March 2nd, 2015
3       April 1st, 2015
4         May 1st, 2015
5        June 1st, 2015
6        July 1st, 2015
7      August 3rd, 2015
8   September 1st, 2015
9     October 1st, 2015
10   November 2nd, 2015
11   December 1st, 2015
12    January 4th, 2016

<h2>Interest Rate</h2>

The InterestRate class can be used to store the interest rate with the compounding type, day count and the frequency of compounding.

In [17]:
annual_rate = 0.05
day_count = ql.ActualActual(ql.ActualActual.ISDA)
compound_type = ql.Compounded
frequency = ql.Annual

interest_rate = ql.InterestRate(annual_rate,
                                day_count,
                                compound_type,
                                frequency)
print(interest_rate)

5.000000 % Actual/Actual (ISDA) Annual compounding

we show that the value returned by compound_factor for 2 years agrees with the
expected compounding formula.

In [18]:
t = 2.0
print(interest_rate.compoundFactor(t))
print((1+annual_rate)*(1.0+annual_rate))

1.1025
1.1025

The discountFactor method returns the reciprocal of the compoundFactor method.

In [19]:
print(interest_rate.discountFactor(t))
print(1.0/interest_rate.compoundFactor(t))

0.9070294784580498
0.9070294784580498

A given interest rate can be converted into other compounding types and compounding frequency using the equivalentRate method.

In [20]:
new_frequency = ql.Semiannual
new_interest_rate = interest_rate.equivalentRate(compound_type,
                                                 new_frequency, t)
print(new_interest_rate)

4.939015 % Actual/Actual (ISDA) Semiannual compounding

The discount factor for the two InterestRate objects, interest_rate and new_interest_rate
are the same

In [21]:
print(interest_rate.discountFactor(t))
print(new_interest_rate.discountFactor(t))

0.9070294784580498
0.9070294784580495

A given interest rate can be converted into other compounding types and compounding frequency
using the equivalentRate method.

In [23]:
new_frequency = ql.Semiannual
new_interest_rate = interest_rate.equivalentRate(compound_type,
                                            new_frequency, t)
print(new_interest_rate)

4.939015 % Actual/Actual (ISDA) Semiannual compounding

The discount factor for the two InterestRate objects, interest_rate and new_interest_rate
are the same, as shown below.

In [24]:
print(interest_rate.discountFactor(t))
print(new_interest_rate.discountFactor(t))

0.9070294784580498
0.9070294784580495

In [28]:
#print(ql.InterestRate.impliedRate())